version: "3.6"
   

services:
  db:
      container_name: data-collection-pg-database-backend
      image: 'postgres'
      ports:
        - '5432'
      networks:
        some_network:
      environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
  core:
    container_name: data-collection-django-core
    build:
      context: .
      dockerfile: Dockerfile-backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      - db
    links:
      - db:db
    networks:
      some_network:

  frontend:
    stdin_open: true
    container_name: data-collection-react-frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./frontend/:/app"
      
networks:
  some_network: