name: Branch Name Check
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Checking current branch name
        run: |
          if [[ ${{ steps.branch-name.outputs.current_branch }} =~ ^[0-9]{4}- ]]; then
              echo ::set-output name=match::true
          fi

      - name: Testing branch name
        if: steps.check-branch.outputs.match != 'true'
        run: |
          echo "The branch name is invalid, must start with 4 numbers and a dash. Such as, 1234-"
          exit 1