name: PR Description Fixed AB# Message Check
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  example:
    name: Checking PR description for AB Linkage
    runs-on: ubuntu-latest
    steps:
    - name: Run actions/checkout 
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run fabiankoestring/body-regex-validator-action
      uses: fabiankoestring/body-regex-validator-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_PATTERN: '^[fF]ix(es|ed)?\sAB#[0-9]{4}'
        PULL_REQUEST_COMMENT: 'This is my pr comment template.'