name: Pull Request Lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  check_pr_branch:
    runs-on: ubuntu-latest
    name: GitLint
    steps:
      - name: Lint commits, branches, and pull requests
        uses: aschbacd/gitlint-action@v1.1.0
        with:
          commit-message-subject-max-length: 100
          re-commit-message-subject: .*
          re-branch-name: '^[0-9]{4}-'
          re-pull-request-title: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)'

  check_pr_title_and_body:
    runs-on: ubuntu-latest
    steps:
      - uses: mtfoley/pr-compliance-action@main
        with:
          title-check-enable: true
          body-regex: '^[fF]ix(es|ed)?\sAB#[0-9]{4}'
          body-comment: 'Please reference the Azure Boards work item ID. Refer to the CONTRIBUTING.md file for more information.'