name: Pull Request Lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

# Action should have write permission to make updates to PR
permissions:
  pull-requests: write

jobs:
  check_pr_branch_and_title:
    runs-on: ubuntu-latest
    name: Check branch and title
    steps:
      - name: Lint commits, branches, and pull requests
        uses: aschbacd/gitlint-action@v1.1.0
        with:
          commit-message-subject-max-length: 100
          re-commit-message-subject: .*
          re-branch-name: '^[0-9]{4}-'
          re-pull-request-title: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)'

  add_pr_description:
    runs-on: ubuntu-latest
    name: Add AB link to PR
    permissions:
      pull-requests: write
    steps:
      - uses: DerekRoberts/action-pr-description-add@v0.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_markdown: |
            Fixed AB#${{ steps.branch-name.outputs.current_branch }}