name: PR Title Check
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^[fF]ix(es|ed)?\sAB#[0-9]{4}'