name: PR Title Check
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: Slashgear/action-check-pr-title@2.0.0
        with:
          regex: '^AB#[0-9]{4}'